GET http://localhost:5000/users

###
GET http://localhost:5000/users/1

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "username": "ghani",
    "password": "1234",
    "confPassword": "1234"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "username": "ghani",
    "password": "1234"
}

###
PATCH  http://localhost:5000/users/2
Content-Type: application/json

{
    "username": "FardanAl",
    "password": "fardan@gmail.com"
}

###
DELETE http://localhost:5000/users/3

###
GET http://localhost:5000/incomes

###
POST http://localhost:5000/users/2/Outcomes
Content-Type: application/json

{
    "name": "Jajan Fardan2",
    "nominal": "3000" ,
    "tanggal_pengeluaran": "5-26-2023"
}

###
GET http://localhost:5000/users/1/Outcomes

###
GET http://localhost:5000/users/2/Outcomes/6

###
PUT http://localhost:5000/users/1/Outcomes/5
Content-Type: application/json

{
    "name": "TopUp",
    "nominal": "85000" ,
    "tanggal_pengeluaran": "5-26-2023"
    
}

###
DELETE http://localhost:5000/users/1/Outcomes/4


###
POST http://localhost:5000/users/1/Incomes
Content-Type: application/json

{
    "name": "Gajian3",
    "balance": "3000000" ,
    "tanggal_pemasukan": "2021-6-26"
}

###
GET http://localhost:5000/users/1/Incomes

###
PATCH http://localhost:5000/Incomes/1
Content-Type: application/json

{
    "name": "Gajian",
    "balance": "1000000" ,
    "tanggal_pemasukan": "5-26-2023"
}



###
POST http://localhost:5000/users/1/JenisPengeluaran
Content-Type: application/json

{
    "nama": "Contoh",
    "persentase": 10
}

###
GET http://localhost:5000/users/1/JenisPengeluaran

###
PUT http://localhost:5000/jenispengeluaran/1
Content-Type: application/json

{
    "nama": "Contoh",
    "persentase": 100
}

###
DELETE http://localhost:5000/jenispengeluaran/1


###
POST http://localhost:5000/users/1/category
Content-Type: application/json

{
    "name": "Contoh2",
    "budget": 300000
}

###
GET http://localhost:5000/users/1/category

###
PUT http://localhost:5000/category/2
Content-Type: application/json

{
    "nama": "Contoh3",
    "persentase": 100
}

###
DELETE http://localhost:5000/jenispengeluaran/1