GET http://localhost:5000/users

###
GET http://localhost:5000/users/1

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "username": "capek",
    "password": "capek@gmail.com" 
}

###
PATCH  http://localhost:5000/users/2
Content-Type: application/json

{
    "username": "Fardan",
    "password": "fardan@gmail.com"
}

###
DELETE http://localhost:5000/users/3

###
GET http://localhost:5000/incomes